[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "Refresh P1 - FTP to Supabase.py && Refresh P2 - Supabase to FTP.py && Refresh P3 - New Entry FTP to Supabase.py"
